# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 43b43aa398b263aa39cc4051fd1f2b374ed819f176d8737f15aa752a0ac01d6133f6ffdb2fdc4d7821ab59faa1d45a9c0f55966b16f8e7ba56b9c1d0b84a3153

test:
  secret_key_base: 03f9abdc3d184f4aaddbb71f524f43b4f9f157792b7f382d6121d3c3d0772b659608b5f2e7ea41e41540464e7aa2f74ede60fa327ce9e548cd486ea9c0fc691f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
